spring.application.name=SeniorHelper

spring.jpa.hibernate.ddl-auto=create
#spring.jpa.hibernate.ddl-auto=create-drop

spring.jpa.open-in-view=false
spring.datasource.url=jdbc:postgresql://localhost:5432/seniorhelper_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

# Ensure data.sql is always executed
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# JWT lifetime (24 hours)
app.security.jwt.ttl-ms=86400000

logging.level.root=INFO
logging.level.edu.fscj.cop3024c.seniorhelper=DEBUG
logging.level.org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver=ERROR
