spring.application.name=SeniorHelper

spring.profiles.default=dev
spring.jpa.open-in-view=false
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

# JWT lifetime (24 hours)
app.security.jwt.ttl-ms=86400000

logging.level.root=INFO
logging.level.org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver=ERROR
